env:
  browser: true
  es6: true
  node: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  eol-last:
    - warn 
  semi:
    - 0
  object-curly-spacing:
    - 0
  arrow-parens:
    - 0

